# config/app.yml for rails-settings-cached
defaults: &defaults
  admin:
    font: "'Helvetica Neue', Helvetica, sans-serif"

    typography:
      h1:
        size: 32
        markdown: "#"
        color: "#444"
      h2:
        size: 24
        markdown: "##"
        color: "#444"
      h3:
        size: 18
        markdown: "###"
        color: "#444"

  author:
    name: "Author Name"
    email: "Author Email"
    twitter: "Author Twitter"
    description: "Author Description"
    about: "Author About"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
