---
admin:
  font: "'Helvetica Neue', Helvetica, sans-serif"
  code_style: atom_one_light
  typography:
    h1:
      size: '32'
      markdown: "#"
      colour: "#444"
    h2:
      size: '24'
      markdown: "##"
      colour: "#444"
    h3:
      size: '18'
      markdown: "###"
      colour: "#444"
author:
  name: Author Name
  email: Author Email
  twitter: Author Twitter
  description: Author Description
  about: Author About
